version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  server:
    build: ./server
    env_file:
      - server/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
  client:
    build: ./client
    env_file:
      - client/.env
    depends_on:
      - server
    ports:
      - "3000:3000"
volumes:
  mongo-data:
