name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm install

      - name: Lint, Typecheck, Test
        run: |
          npm run lint
          npm run typecheck
          npm run test

      - name: Build Client & Server
        run: |
          npm run build:prod
