name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm install

      - name: Lint Frontend (non-blocking)
        run: |
          cd client
          npm install --legacy-peer-deps --no-audit --progress=false
          npm run lint || true  # continue even if lint errors

      - name: Typecheck (client only, non-blocking)
        run: npx tsc -p client/tsconfig.json --noEmit || true

      - name: Test (placeholder)
        run: npm run test

      - name: Build Client & Server
        run: |
          npm run build:prod
